GET http://localhost:3000/users

### login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "kanboomsquad05@gmail.com",
    "password": "password"
}

### reset-password
POST http://localhost:3000/users/reset_password
Content-Type: application/json

{
    "email": "elcio@gmail.com",
    "password": "elcio-pass"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "KanboomUser",
    "email": "kanboomsquad05@gmail.com",
    "password": "password"
}

### post a invalid user email
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "mariagmail.com",
    "password": "password"
}

### -------------------------- TEST BOARD ---------------------------------------- ###

### RETRIEVE ALL BOARD
GET http://localhost:3000/board

### RETRIEVE ALL BOARD BY USER ID
GET http://localhost:3000/board/user/64769ce1e4b7c84bdc9a3a31

### RETRIEVE BOARD BY ID
GET http://localhost:3000/board/646c12ed7e120f818971366a

### SAVE BOARD
POST http://localhost:3000/board
Content-Type: application/json

{
  "userId": "64769ce1e4b7c84bdc9a3a31",
  "name": "kanboom-teste1"
}


### -------------------------- TEST COLUMN ---------------------------------------- ###

### RETRIEVE ALL COLUMN
GET http://localhost:3000/column

### RETRIEVE ALL COLUMN BY BOARD ID
GET http://localhost:3000/column/board/646c12ed7e120f818971366a


### RETRIEVE ONE
GET http://localhost:3000/column/646c135e7e120f8189713672

### SAVE COLUMN
POST http://localhost:3000/column
Content-Type: application/json

{
  "boardId": "646c12ed7e120f818971366a",
  "name": "TO-DO1"
}

### UPDATE COLUMN
PATCH http://localhost:3000/column/6468cb0934e71feab0db6c70
Content-Type: application/json

{
  "boardId": "64665a42082ab33beaea6826",
  "name": "DONE"
}

### -------------------------- TEST CARD ---------------------------------------- ###

### RETRIEVE ALL CARD
GET http://localhost:3000/card

### RETRIEVE ALL CARD BY COLUMN ID
GET http://localhost:3000/card/column/646d6adbb207bc60b05857b9


### RETRIEVE ONE
GET http://localhost:3000/card/64700c0009839a70e517c900

### DELETE
DELETE http://localhost:3000/card/64700e5fe9ce4b2e9d49bee2

### SAVE CARD
POST http://localhost:3000/card
Content-Type: application/json

{
  "name": "TO-DO2",
  "column": "646d6adbb207bc60b05857b9"
}

### UPDATE CARD
PATCH http://localhost:3000/card/64700c0009839a70e517c900
Content-Type: application/json

{
  "column": "646d6adbb207bc60b05857b9",
  "name": "CARD 2",
  "description": "this is the description of the card 2"
}


### -------------------------- EMAIL ---------------------------------------- ###


### RECOVERY EMAIL
POST http://localhost:3000/email/recovery/kanboomsquad05@gmail.com

### RECOVERY EMAIL WHEN NOT FOUND
POST http://localhost:3000/email/recovery/fake@gmail.com
