GET http://localhost:3000/users

### login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "elcio@gmail.com",
    "password": "password"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "maria@gmail.com",
    "password": "password"
}

### post a invalid user email
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "mariagmail.com",
    "password": "password"
}

### -------------------------- TEST BOARD ---------------------------------------- ###

### RETRIEVE ALL BOARD
GET http://localhost:3000/board

### RETRIEVE ALL BOARD BY USER ID
GET http://localhost:3000/board/user/645c222269992d3715626b59

### SAVE BOARD
POST http://localhost:3000/board
Content-Type: application/json

{
  "userId": "645c222269992d3715626b59",
  "name": "kanboom-teste1"
}


### -------------------------- TEST COLUMN ---------------------------------------- ###

### RETRIEVE ALL COLUMN
GET http://localhost:3000/column

### RETRIEVE ALL COLUMN BY BOARD ID
GET http://localhost:3000/column/board/64665a42082ab33beaea6826


### RETRIEVE ONE
GET http://localhost:3000/column/6468cb0934e71feab0db6c70

### SAVE COLUMN
POST http://localhost:3000/column
Content-Type: application/json

{
  "boardId": "64665a42082ab33beaea6826",
  "name": "TODO"
}

### UPDATE COLUMN
PATCH http://localhost:3000/column/6468cb0934e71feab0db6c70
Content-Type: application/json

{
  "boardId": "64665a42082ab33beaea6826",
  "name": "DONE"
}
